# for row in range(5):
#     for column in range(4):
#         if (row==0 and column%3!=0) or (row==2 and column%3!=0) or (row!=0 and column==0) or (row!=0 and column==3):
#             print("*", end=" ") 
#         else:
#             print(" ",end=" ")      
#     print()

# print()

# for row in range(5):
#     for column in range(6):
#         if (column==0 or (column==3 and (row%2!=0)))or ((row==0 or row==2 or row==4) and column<3):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()


# print()


# for i in range(6):
#     for j in range(4):
#         if (j==0 and i%5!=0) or(j!=0 and i%5==0):
#             print("*", end=" ")
#         else:
#             print(" ",end=" ")
#     print()



# print()
 

# for i in range(7):
#     for j in range(5):
#         if (j==0) or (i==0 and j%4!=0) or (i==6 and j%4!=0) or (i%6!=0 and j==4):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()



# print()


# for i in range(7):
#     for j in range(5):
#         if (j==0) or (i==0) or (i==3) or (i==6):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()



# print()

# for i in range(7):
#     for j in range(5):
#         if (j==0) or (i==0) or (i==3):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()


# print()

# for i in range(7):
#     for j in range(5):
#         if (j==0) or (i==0) or (i==6) or (j!=1 and i==4) or (i==5 and  j==4):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()



# print()
   

# for i in range(7):
#     for j in range(5):
#         if (j==0) or (j==4) or (i==3 and j%4!=0):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()
   
# for i in range(7):
#     for j in range(5):
#         if j==0:                                                                                                                                               #             print("    ",end=" ")
                                                                  
#             print("*",end=" ")
#         else:
#             print("    ",end=" ")
#     print() 

# print()


# for i in range(6):
#     for j in range(5):
#         if (i==0) or (j==2) or(i>2 and j==0):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(7):
#     for j in range(5):
#         if (j==0) or(i+j==3) or (i-j==3):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(7):
#     for j in range(5):
#         if j==0 or i==6:                                                                                                                                               #             print("    ",end=" ")
                                                                  
#             print("*",end=" ")
#         else:
#             print("    ",end=" ")
#     print() 

# print()

# for i in range(5):
#     for j in range(5):
#         if (j==0) or (j==4) or (i==1 and j==1) or (i==2 and j==2) or(i==1 and j==3):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(5):
#     for j in range(5):
#         if (j==0) or (j==4) or (i==j):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(7):
    # for j in range(5):
    #     if (i==0 and j%4!=0) or (i==6 and j%4!=0)or (i%6!=0 and j==0) or (i%6!=0 and j==4):
    #         print("*",end=" ")
    #     else:
    #         print(" ",end=" ")
    # print()

# print()

# for row in range(7):
#     for column in range(5):
#         if (column==0) or (column!=4 and row==0) or (row==3 and column!=4)or (row==1 and column==4) or (row==2 and column==4) :
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(7):
#     for j in range(5):
#         if (i==0 and j%4!=0) or (i==6 and j%4!=0)or (i%6!=0 and j==0) or (i%6!=0 and j==4) or (i==4 and j==2) or (i==5 and j==3):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(7):
#     for j in range(5):
#         if (j==0) or (j!=4 and i==0) or (i==3 and j!=4)or (i==1 and j==4) or (i==2 and j==4)or (i-j==2):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()


# print()

# for i in range(7):
#     for j in range(5):
#         if (i==0 and j!=0)or(i==6 and j!=4)or(i==3 and j%4!=0)or(i==1 and j==0) or (i==2 and j==0)or (i==4 and j==4)or (i==5 and j==4):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(6):
#     for j in range(5):
#         if (i==0) or (j==2):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")

#     print()
# print()

# for i in range(7):
#     for j in range(5):
#         if (i==6 and i%4!=0) or (j==0) or (j==4):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ") 

#     print()

# print()

# for i in range(7):
#     for j in range(5):
#         if (i==0 and j==0) or (i==0 and j==4) or (i==2 and j==0) or (i==2 and j==4) or (i==4 and j==1) or (i==4 and j==3) or (i==6 and j==2):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")

#     print()

# print()

# for i in range(7):
#     for j in range(5):
#         if (j==0) or (j==4)or(i==4 and j==2)or (i==5 and j==1) or (i==5 and j==3):
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(5):
#     for j in range(5):
#         if i==j or i+j==4:
#                  print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()

# for i in range(7):
#     for j in range(5):
#         if i==j==0 or i==j==1 or i+j==4:
#                  print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()
# for i in range(7):
#     for j in range(5):
#         if i==0 or i==6 or i+j==5:
#                  print("*",end=" ")
#         else:
#             print(" ",end=" ")
#     print()

# print()